version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]

    blackfire:
        image: blackfire/blackfire
        env_file: .env.local
        ports: [8707]